### ISSUE TITLE
Clojure support

### ISSUE THREAD

**Issue by daveyarwood** [connorwalsh/new-yorken-poesry-magazine#51]
So I tried to upload a poet written in Clojure, but the backend sent this 400 response:

> poet language (clojure) not supported (╥﹏╥)

AFAICT from digging into the source, the issue is that [the backend will only accept Python as a valid language when creating a poet](https://github.com/connorwalsh/new-yorken-poesry-magazine/blob/f9fc3393fe01da8a33b96208cc56b74a9c7cdf1a/server/core/poet_handlers.go#L256-L259).

I'm happy to dive in and start working on a fix, if you'd like. It seems like the best thing to do would be to determine the languages actually supported by the backend somehow (maybe xaqt offers some way?), but a next-best effort might be to just hard-code the rest of the for-sure-supported languages into the place I linked above for now.

**Comment by connorwalsh** [comment]
@daveyarwood nice catch! thanks! `pipi_sauvage` just pushed a fix for this-- turns out that these languages *are* supported but the list of supported langs being passed to the validator for poet creation was outdated/hardcoded.

you can see the PR here https://github.com/connorwalsh/new-yorken-poesry-magazine/pull/52
